#!/bin/bash
source /usr/local/bin/resty -W 'http://localhost:8091/pools/default'
source /etc/bash.bashrc

function logIt() {
	logFile="/storage/locker.log"
	timestamp=$( date )
	if [ -z "$2" ];then
		severity="INFO"
	else
		severity="$2"
	fi
	hostname=`hostname`
	facility_label="user-level"
	facility=1
	echo "{ \"timestamp\": \"$timestamp\", \"host\": \"${hostname}\", \"server_software\": [ ], \"facility_label\": \"${facility_label}\", \"severity\":\"$severity\", \"message\": \"$1\" }" >> $logFile
}

function setKeys() {
	if [ -z "$PRIVATE_KEY" ];then
		cp /root/.ssh/container-key /root/.ssh/id_rsa 
		cp /root/.ssh/container-key.pub /root/.ssh/id_rsa.pub 
	else
		echo "$PRIVATE_KEY" > /root/.ssh/id_rsa
		chmod 600 /root/.ssh/id_rsa
		# NOTE: can't get keys with passcodes working at the moment; will come back to this later
		sudo ssh-agent -a /tmp/agent.sock
		export SSH_AUTH_SOCK=/tmp/agent.sock
		sshpass -p$PASSWORD sudo ssh-add /root/.ssh/id_rsa
		ssh-keygen -yf /root/.ssh/id_rsa -C "id_rsa_nopass" > /root/.ssh/id_rsa.pub
	fi
}

function storageListing() {
	echo "";
	echo "Docker Locker contents:";
	echo "-----------------------";
	ls -al --color=yes "/storage/$1"
	echo "";
	echo "Disk Usage:";
	du -s "/storage/$1" 
}

# allows calling host to specify what package managers (or other commands) to run to prepare the data for usage
function prepStorage() {
	evilCommands=`echo $PREP | jsawk -n 'out(this)' | cut -d '"' -f 2 | cut -d "'" -f 2`

	# IFS=$'\n';
	cd /app/data
	cmd=( composer install )
	"${cmd[@]}"
	# composer.phar install
	# for cmd in $evilCommands;do
	# 	echo "";
	# 	echo "Executing: $cmd"
	# 	echo "";
	# 	cd /app/data;
	# 	`"$cmd"`
	# done
	unset IFS;
}

# Note: this isn't being used currently as these dependencies are statically included in 
# the docker image. Keeping this here in case there's a desire to introduce run-time optionality back in.
function languageSupport() {
	if [[ "$SUPPORT" == *composer* ]];then
		if [ -z `which php` ];then
			# install Ubuntu sourced dependencies
			apt-get install -yqq php5 curl
			cd /app
			# install Composer
			curl -sS https://getcomposer.org/installer | php
			mv composer.phar /usr/local/bin/composer
			chmod +x /usr/local/bin/composer
		fi
	fi
	if [[ "$SUPPORT" == *bower* ]];then
		if [ -z `which npm` ];then
			apt-get install -yqq curl
			curl -sL https://deb.nodesource.com/setup | sudo bash -
			apt-get install -yqq nodejs
		fi
		if [ -z `which bower`]; then
			npm install bower
		fi
	fi
}

function entryAlias() {
	if [ -n "$ENTRY_ALIAS" ];then
		echo "ENTRY ALIAS set to $ENTRY_ALIAS";
		cd /app/data
		if [ -d "/app/data/dist" ]; then
			ln -s /storage/dist "$ENTRY_ALIAS"
		elif [ -d "/app/data/public" ]; then
			ln -s /storage/public "$ENTRY_ALIAS"
		fi
	fi
}

function updatePackageManagers() {
	echo "";
	echo "Updating dependencies managed by package managers"
	echo "";
	cd /app/data
	if [ -e "/app/data/composer.json" ]; then
		echo "- found Composer; updating ...";
		composer update
	fi
	if [ -e "/app/data/bower.json" ]; then
		echo "- found Bower; updating ...";
		bower update
	fi
	if [ -e "/app/data/package.json" ]; then
		echo "- found NPM; updating ...";
		npm update
	fi
	echo "";
	echo "All package managers have been updated!"
}

function catFile() {
	if [ -f "/app/data/$1" ]; then
		cat "/app/data/$1"
	else
		echo "Couldn't find $1";	
	fi
}

function allDone() {
	echo "";
	echo "";
	echo "- All done. Locker ready for use.";
	echo "";
}

case "$1" in
	about)
		cat /app/resources/docker.txt
		cat /app/resources/locker.txt
		echo "";
		echo "Locker Docker v$LOCKER_VERSION";
		echo "---------------------";
		echo "a great place to put your stuff!";
		echo "";
		echo "Container Public Key:"
		echo "---------------------"
		cat /root/.ssh/container-key.pub
	;;
	public-key)
		setKeys;
		if [ -e /root/.ssh/id_rsa.pub ];then 
			cat /root/.ssh/id_rsa.pub
		else
			cat /root/.ssh/container-key.pub
		fi
	;;
	load)
		setKeys;
		if [[ "$2" =~ "bitbucket." ]] || [[ "$2" =~ "github." ]];then 
			logIt "Loading locker with git repo: $2"
			echo "- Assuming source type is a git repo";
			if [ -z "$BRANCH" ];then 
				BRANCH='master'
			fi
			git clone -b $BRANCH $2 /app/data
			echo "- Repo has been cloned; branch set to "$BRANCH
			echo "";
			if [ -n "$PREP" ];then
				prepStorage;
			fi
			entryAlias;
			storageListing;
			allDone;
		elif [[ "$2" =~ ".tar" ]]; then
			echo "- Assuming source type is a tarball";
			echo "- Not yet implemented; exiting ...";
			exit 1;
		else
			echo "- Unknown source type; quitting.";
			exit 1;
		fi
	;;
	empty)
		echo "Creating an empty data locker";
		allDone;
	;;
	ls)
		storageListing "$2";
	;;
	cat)
		catFile "$2";
	;;
	pull)
		setKeys;
		echo "Pulling Latest from Repo";
		cd /storage/
		git pull
		echo "- git repo has been pulled"
		storageListing;
	;;
	update-dep)
		setKeys;
		updatePackageManagers;
	;;
	status)
		echo "";
		echo "Git repo's status:";
		cd /app/data
		git status 
		echo "";
		git branch -v --color=always
		echo "";
	;;
	branch)
		cd /app/data
		git branch | cut -d " " -f 2
	;;
	hashtag)
		cd /app/data
		git branch -v | cut -d " " -f 3
	;;
	
esac
